platform :ios, '13.4'
use_frameworks!

target 'routine-kmp' do
  
  pod 'shared', :path => '../../shared/'
  
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
end
